### PR TITLE
Fixed path normalize on Windows, Alternative file extension, can.view.attr

### PR DESCRIPTION
**Pull request by srasp**
Added extension mapping, if you use another view extension as ".mustache", eg. ".mst". Just added "extension" parameter to the options.
If can.view.attr is used, it wasn´t take into account. Added an options parameter to maintain used view attrs.

Signed-off-by: srasp <sebastian.rasp@promerit.com>

### CODE REVIEW

**Comment by daffl** [comment]
Awesome thank you! Two things: The [build failed](https://travis-ci.org/daffl/can-compile/builds/51049211#L180) with a JSHint error (the variable `i` is defined twice in https://github.com/srasp/can-compile/blob/master/lib/compile.js#L51 and https://github.com/srasp/can-compile/blob/master/lib/compile.js#L57).

Could you also add the documentation for the `extension` parameter (probably somewhere around https://github.com/daffl/can-compile#programmatically) and add it as an option in the command line at https://github.com/daffl/can-compile/blob/master/bin/can-compile#L12).

**Comment by srasp** [comment]
As you recommended I changed the variable in compile.js and added the parameters to the documentation as well as in the command line at can-compile.

**Comment by marshallswain** [comment]
@srasp  It looks like the automated tests have failed again.  You can click the details link to the right of the message that says "The Travis CI build failed" to see what's going on.  You can actually run these tests yourself before pushing your code, as well.  Have you tried running the tests on your own machine?  If you're not familiar with the process, this is how to get it working:

- Make sure you have [Grunt installed globally](http://gruntjs.com/getting-started#installing-the-cli).  
- Open the root folder of this project in a terminal window and do `npm install` 
- then run `grunt test`.  Actually, you can just run `grunt`, since the default grunt task is set to test, [in Gruntfile.js](https://github.com/daffl/can-compile/blob/master/Gruntfile.js#L25).  It looks like it will be running JSHint on your code, too, based on the next line of code.  

If the tests run without any errors and you're cleaning up anything JSHint says to fix, the Travis CI builder won't balk at your awesome commits.

**Comment by daffl** [comment]
That's a weird error though. I'll check what's going on.

**Comment by srasp** [comment]
Sorry guys, now it should work. I had to check if the new option `extensions` is defined.
I´ve updated the test, because on Windows the normilzer method didn´t work. Additonally, I´ve added a test case, to test the alternative file extension.

**Comment by marshallswain** [comment]
No need to apologize.  Thank you for your work.

**Comment by daffl** [comment]
Awesome, thank you!

**Comment by daffl** [comment]
Released as version 0.8.0. Thanks again!

**Pull request merged**
